### ISSUE TITLE
Atuin doesn’t clear the screen with MOSH, works fine with SSH

### ISSUE THREAD

**Issue by Abmvk** [atuinsh/atuin#1845] opened 2024-03-10 15:23 UTC
I use atuin on a Raspberry Pi, that connects with an iPad over MOSH (or SSH if I have to). When Atuin opens after arrow-up, it doesn’t clear the screen, and doesn’t restore it when Atuin finishes. Using SSH it all works fine. So no big issue, but if a solution exists, I would be happy :)

Thanks!

**Comment by ellie** [comment] 2024-03-10 17:23
This is because mosh doesn't handle altscreen properly, which Atuin needs. If you use screen/tmux/etc, the problem should be resolved

Otherwise, dupe of #1324

**Closed by ellie** 2024-03-10 17:23 UTC

**Comment by Abmvk** [comment] 2024-03-10 18:51
Thank you!Met vriendelijke groet,Arnout van KempenOp 10 mrt 2024 om 18:24 heeft Ellie Huxtable ***@***.***> het volgende geschreven:﻿
This is because mosh doesn't handle altscreen properly, which Atuin needs. If you use screen/tmux/etc, the problem should be resolved
Otherwise, dupe of #1324
