### ISSUE TITLE
Arrow keys stops working

### ISSUE THREAD

**Issue by mindriddler** [atuinsh/atuin#1292] opened 2023-10-07 12:15 UTC
**Describe the bug**
When using atuin to run a python command the up and down arrows stops working inside the python code when its needed for a interactive choice. See this [video](https://asciinema.org/a/UcGfvICjRxsPEkskMoOBM67Np)

**To Reproduce**
1. Clone this repo `https://github.com/mindriddler/atuin-arrow-keys.git`
2. Create venv `python -m venv venv`
3. Activate venv `source venv/bin/activate`
4. Install requirements `pip install -r requirements.txt`
5. Run code `python main.py`
6. Try using the arrow keys
7. If `python main.py` is ran directly from the terminal it should work each time until command is pulled from atuin history
8. Try run `python main.py` when its pulled from atuin history
9. Should not work anymore
10. Use `reset` command or any other terminal appliation (i have tried using lazygit) to reset the shell
11. `python main.py` directly from the terminal should work again

**Expected behavior**
I expect my arrow keys to still be working inside the python code after i pull the command from atuin history

**Device (please complete the following information):**
 - OS: Arch Linux
 - Shell: zsh/bash
 - Version: 16.0.0

**Comment by ellie** [comment] 2023-10-17 22:23
This is resolved in `main`! Confirmed on macOS, with zsh, and latest Atuin from source. I suspect it's because of #1170

**Closed by ellie** 2023-10-17 22:23 UTC
Labels: bug

**Comment by ellie** [comment] 2023-10-17 22:24
Also thank you so much for providing such an easily replicate-able test case! Very helpful 🙏

**Comment by mindriddler** [comment] 2023-10-18 14:35
Will be waiting the release of v17 to test it out and see if it works then. But in the meantime, thank you so much for fixing the issue!
