### ISSUE TITLE
Add tags and descriptions to history records

### ISSUE THREAD

**Issue by bobhenkel** [atuinsh/atuin#1897] opened 2024-03-22 03:46 UTC
First I really love Atuin, thanks for making it!  

I was wondering how hard it would be to have the ability to add tags and a description to a entry?

Say I have a command in my history like "awesome command goes here". I'd love to go back in my history and mark this entry with one or more tags of #execute-launch-sequence and a description of launch rockets to pluto, be careful not to run on a full moon.  Maybe something that helps me describe what this command does so that future me can search for the description text and get an overview of what past me created it for etc.

Now if I have tags on hundreds of handy commands from my history I could also now in addition for just searching for awesome and finding it my history type #execute-launch-sequence and any history I tagged as such would show up.  And the same with the description data.

Just thought I would ask.

Thanks
Bob

**Comment by bobhenkel** [comment] 2024-03-22 03:48
Relates to https://github.com/atuinsh/atuin/issues/1115

**Comment by mateuscomh** [comment] 2024-07-05 11:02
Hi,

I also thought about a suggestion like this. Actually, I had thought of tags to indicate the origin of the command (on which host it was saved) and displayed in the Atuin history.

However, for what you mentioned, something that might help is to add a "#" at the end of your future commands to comment and make it easier to search in the future:
```
$ echo "command" #This is important
```

**Comment by ellie** [comment] 2024-07-05 13:35
Thanks for the input here! I'll close this one as a dupe of #1115 for now, but I am interested in the feature as a whole.

**Closed by ellie** 2024-07-05 13:35 UTC
