### ISSUE TITLE
[Feature] Hide columns in TUI history view

### ISSUE THREAD

**Issue by vbfox** [atuinsh/atuin#2413] opened 2024-10-08 08:20 UTC
I find some of the columns in the history view (when Ctrl+R is pressed) distracting.

<img width="425" alt="Screenshot 2024-10-08 at 10 12 55" src="https://github.com/user-attachments/assets/743bb57c-06d0-41eb-bd74-f622396c1950">

I'd like to be able to hide them. I saw that #1616 was similar but requesting a full format for the non-TUI side, while I specifically would want to change the TUI part.

I did the change on a branch https://github.com/vbfox/atuin/commits/optional-search-columns to add booleans to hide each of the column but seeing that the command line is driven by a full format I wonder if the TUI should too (With the potential added complexity)

So opening this issue to see if the feature could interest the project and what direction it should take if it does.

**Comment by gigberg** [comment] 2024-10-11 18:29
it can be better if tui can support display {directory} field like which "atuin history list -f " does.

**Comment by ellie** [comment] 2024-10-11 18:38
I'm gonna close this one as a dupe of #998

**Closed by ellie** 2024-10-11 18:38 UTC
