### ISSUE TITLE
JSON schema for `config.toml`

### ISSUE THREAD

**Issue by niklasravnsborg** [atuinsh/atuin#2161] opened 2024-06-18 15:49 UTC
Having a schema for the `config.toml` file that Atuin uses would be highly beneficial. This would not only facilitate easier editing of configurations but could also enable auto-generation of documentation tables or other useful outputs.

Schemas can be integrated using the `$schema` key to enable editor completions:

```toml
"$schema" = 'https://example.org/schema.json'
```

For reference, here are a few example schema files:
- [Starship](https://github.com/starship/starship): https://starship.rs/config-schema.json
- [Yazi](https://github.com/sxyazi/yazi): https://raw.githubusercontent.com/yazi-rs/schemas/main/schemas/yazi.json
- [Alacritty](https://github.com/alacritty/alacritty): https://raw.githubusercontent.com/distinction-dev/alacritty-schema/main/alacritty/reference.json

Resources for creating a schema:

- [Writing a schema](https://json-schema.org/learn/getting-started-step-by-step)
- [Adding a schema to JSON Schema Store](https://github.com/SchemaStore/schemastore/blob/master/CONTRIBUTING.md#how-to)

**Comment by ellie** [comment] 2024-06-18 16:03
Hey! Thanks for the issue

This one is a dupe of #1626 

I'm aware of what they are and am not opposed to having one, but I'd rather not have it something that we have to maintain manually

**Closed by ellie** 2024-06-18 16:03 UTC
