### ISSUE TITLE
Alt doesn't work on Mac

### ISSUE THREAD

**Issue by jucor** [atuinsh/atuin#761] opened 2023-03-06 13:37 UTC
Hi @ellie !
Sorry to bother you, but I think on Mac the Alt key (or more precisely the Option key on Mac) are not at all recognised by Atuin. See also #417. 
I suspect the crux is in recognizing the Option modifier on this line: https://github.com/ellie/atuin/blob/e9c5e1d85c5c1d3310fb7994c474f9462c0bca97/src/command/client/search/interactive.rs#L98 
I'm not familiar with the `crossterm` lib, nor with Rust, so not sure how to implement this, apologies.
Thanks for the great tool!

**Comment by jucor** [comment] 2023-04-11 14:05
Yes, can merge both and rename #417 to show it goes beyond Alt+N.

**Comment by ellie** [comment] 2023-10-18 03:01
Hey! Sorry I totally missed this one - but yes you're right, it's a dupe of #417

We don't use it beyond the alt-n shortcut, and I'll probably avoid adding anything to alt in the future :D

**Closed by ellie** 2023-10-18 03:01 UTC
