### ISSUE TITLE
Accepting history hangs with network

### ISSUE THREAD

**Issue by jedbrown** [atuinsh/atuin#1381] opened 2023-11-07 04:04 UTC
**Describe the bug**
Sometimes a network is "connected", but no packets actually get through. This happens when drifting out of wifi range, various service interruptions, or on an isolated LAN. One can still search history, but pressing enter hangs indefinitely instead of accepting the line. This is especially awkward when one is interrogating why the network is dysfunctional.

**To Reproduce**
1. Be "connected" without external connectivity (e.g., connect to router without modem or block with a firewall).
2. Press up arrow or rsearch to select a command, then press enter to accept.
3. atuin hangs

**Expected behavior**
Accept and execute the command, possibly alerting and possibly caching the local history for when connectivity returns.

**Error logs**
Please try and provide error logs where possible

**Device (please complete the following information):**
 - OS: Linux
 - Shell bash and zsh
 - Version 17.0.1

**Self hosted**
Not self-hosted

**Comment by ellie** [comment] 2023-11-07 20:53
Does this occur every single time? Does it also occur with `update_check = false` in your config?

Super weird because Atuin doesn't do any network interaction explicitly when selecting some history

**Comment by jedbrown** [comment] 2023-11-08 01:37
I think so, at least that was my first indicator of network issues on many occasions and went away when it returned. I have set `update_check = false` and will report back/try to get a stack trace if I can reproduce. Thanks!

**Comment by mateuscomh** [comment] 2023-11-20 15:19
@ellie "I had the same issue when I was without internet for a while. When I performed the recursive search and ran the command, the terminal wouldn't display anything and only released after a Ctrl+C interrupt."

OS: Linux
Bash
Versão 17.0.1

**Comment by ellie** [comment] 2023-11-20 15:20
> @ellie "I had the same issue when I was without internet for a while. When I performed the recursive search and ran the command, the terminal wouldn't display anything and only released after a Ctrl+C interrupt."
> 
> OS: Linux Bash Versão 17.0.1

Do you have any steps to reproduce?

I've worked pretty regularly from trains and airplanes without internet over the past year or two, and not had this issue. I'll see what I can do though.

**Comment by mateuscomh** [comment] 2023-11-21 17:21
> > @ellie "I had the same issue when I was without internet for a while. When I performed the recursive search and ran the command, the terminal wouldn't display anything and only released after a Ctrl+C interrupt."
> > OS: Linux Bash Versão 17.0.1
> 
> Do you have any steps to reproduce?
> 
> I've worked pretty regularly from trains and airplanes without internet over the past year or two, and not had this issue. I'll see what I can do though.

I was able to reproduce the behavior as follows: First, I am connected to the internet and to my router with cable, and I can use Ctrl+R. Therefore, if I lose communication with the internet but my communication with the local router remains established, this behavior of the recursive search not displaying anything on the screen occurs. 

I can create a video to demonstrate this behavior if it helps. Please let me know the best way to share it.

**Comment by ellie** [comment] 2023-11-21 17:23
Thank you for the steps! A video would be amazing (I'm pretty sure you can just upload straight to issues), though I should be able to replicate with that

**Comment by azerupi** [comment] 2023-12-10 03:31
To narrow it down a bit, the call that makes everything hang is here:

https://github.com/atuinsh/atuin/blob/bdd7fe661f5157dd30bb0dd07006bfa97555b8f6/atuin/src/command/client/search/interactive.rs#L626

This then makes a get request to retrieve the latest version number available. And I believe it hangs on DNS resolution.

**Comment by conradludgate** [comment] 2023-12-10 11:45
DNS lookups happen in a background thread. I'm not sure how they would be the cause of the interruption here 🤔

https://docs.rs/hyper/0.14.27/src/hyper/client/connect/dns.rs.html#121-126

**Comment by azerupi** [comment] 2023-12-11 00:27
My understanding is that the tokio runtime will wait on the blocking task to finish before exiting. So while the main task of atuin is done, the dns task is still running in the background and thus tokio waits for it to finish. This prevents atuin from exiting and giving back control to the shell.

Simplified example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=5b6342ea02412c59dda47c212b794185

**Comment by ellie** [comment] 2023-12-16 21:42
Should be resolved in #1381

**Closed** 2023-12-16 21:42 UTC
Labels: bug
