### ISSUE TITLE
Delete history entry without having to type it again (thereby adding it to history once more)

### ISSUE THREAD

**Issue by masaeedu** [atuinsh/atuin#1245] opened 2023-09-20 22:18 UTC
**Is your feature request related to a problem? Please describe.**

I'm trying to purge the shell history of a command involving a password. I execute such commands on rare occasions, either on purpose if I'm too lazy to put the password in a file yada yada yada, or by accident (if I mispredict what's on my clipboard). Either way, with normal zsh history my workflow was just to open the .zsh_history file and delete the offending line.

With atuin, IIUC the release notes [here](https://atuin.sh/blog/release-v14), the idea is to execute:

> `atuin search --delete --search-mode <command including the password>`

While this deletes the original entry, it adds another one for the `atuin search --delete` invocation, also containing the password. This defeats the purpose of the redaction.

**Describe the solution you'd like**

A way to delete a history entry by (in decreasing order of preference)...

***Explicitly selecting it in the interactive UI and pressing a hotkey***
  
I thought the slightly more inconvenient alternative of using `atuin search --delete -i` might work, but selecting the relevant entry just prints it out, and it's still there next time I search.

***Referring to an identifier for the history entry***

Specifically, a GUID or something that I can discover via the interactive UI, and that doesn't include the text of the actual entry.

***Referring to an offset representing the nth last command***

At first glance this would seem to already be supported, but I tried several variations and couldn't get it to work. I'm either holding it wrong or there's other bugs:

```
❯ atuin search --delete --offset=3
Error: error returned from database: (code: 1) near "OFFSET": syntax error

Caused by:
    (code: 1) near "OFFSET": syntax error

Location:
    src/command/client/search.rs:173:19

~ via 🐍 v3.10.12
❯ atuin search --delete --offset 4
Error: error returned from database: (code: 1) near "OFFSET": syntax error

Caused by:
    (code: 1) near "OFFSET": syntax error

Location:
    src/command/client/search.rs:173:19

❯ atuin search --delete --offset 5 --limit 1
deleting 3cc83cbb0e4a458f8bae1479bf4df85b
deleting 3cc83cbb0e4a458f8bae1479bf4df85b
... <infinite loop>
deleting 3cc83cbb0e4a458f8bae1479bf4df85b
deleting 3cc83cbb0e4a458f8bae1479bf4df85b
^C
```

**Comment by ellie** [comment] 2023-09-20 22:21
We don't save commands that start with a space, so you could prepend your delete command with a space

**Comment by ellie** [comment] 2023-09-20 22:24
Otherwise, dupe of #854

**Closed** 2023-09-20 22:25 UTC
Labels: enhancement
