### ISSUE TITLE
How can I highlight the characters I have typed when using fzf?

### ISSUE THREAD

**Issue by franroa** [atuinsh/atuin#1674] opened 2024-02-05 06:43 UTC
Hi there, I was looking for an option to see the word highlighted which I have typed in order to find my history.
Does atuin have a way of doing this?

Thanks!

**Comment by ellie** [comment] 2024-02-05 15:23
Not at the moment I'm afraid

Dupe of #503

**Closed by ellie** 2024-02-05 15:23 UTC
