### ISSUE TITLE
Deleted records show in interactive search

### ISSUE THREAD

**Issue by Aridor2006** [atuinsh/atuin#1187] opened 2023-08-21 17:56 UTC
Hello, I'm using 16.0 with fish shell and while the regular search doesn't seem to return deleted records, they do show up in interactive search as some kind of hash (and therefore also when doing up arrow). Is there a way to change that behavior or permanently delete them?

![image](https://github.com/atuinsh/atuin/assets/3269398/a2409842-7a35-4325-991a-6481602b1551)

**Comment by deicon** [comment] 2023-09-29 10:50
Duplicate of #1207

**Closed** 2023-10-12 19:54 UTC
