### ISSUE TITLE
Atuin keeps recreating `~/.config/atuin/config.toml`

### ISSUE THREAD

**Issue by jjant** [atuinsh/atuin#1724] opened 2024-02-15 17:11 UTC
I just ran into this issue:

```terminal
❯ ls ~/.config/atuin/
Permissions  Size User     Date Modified Name
.rw-r--r--  4.9Ki jjantdev 15 Feb 17:09  config.toml

❯ rm -rf ~/.config/atuin/config.toml && ls ~/.config/atuin/

❯ ls ~/.config/atuin/
Permissions  Size User     Date Modified Name
.rw-r--r--  4.9Ki jjantdev 15 Feb 17:09  config.toml
```

Somehow the config file keeps getting recreated. This is annoying because I'm trying to configure my atuin with [HomeManager](https://github.com/nix-community/home-manager/) but it refuses to create its own `~/.config/atuin/config.toml` because there already an existing one that it doesn't own.

**Comment by xvello** [comment] 2024-02-21 10:41
Heya @jjant, this means that the shell hooks for atuin are already installed, and `atuin` is called before and after each command, to record the history.

You'll have to first disable the atuin hooks. If you enabled it through home manager, set ` programs.atuin.enable = false`, restart your shell, delete the file, then re apply your HM config with atuin re-enabled and a config specified. If you installed atuin another way, remove it first, as HM will use nixpkgs's package anyway.

**Comment by jjant** [comment] 2024-02-21 11:05
Hi @xvello, thanks for the help! I'll try that.

**Comment by iwahbe** [comment] 2024-03-02 16:59
This is a duplicate of https://github.com/atuinsh/atuin/issues/1180.

**Closed** 2024-03-02 17:11 UTC
Labels: duplicate
