### ISSUE TITLE
Commands prefixed with '#' aren't saved to history

### ISSUE THREAD

**Issue by JonnyKelso** [atuinsh/atuin#594] opened 2022-11-04 15:05 UTC
In bash (and zsh etc), when you prefix a command with the '#' character and hit return it gets saved to your history but does NOT get executed.
This is really useful if you're in the middle of building a long command and forget you need to run another command first, just preix the command with '#', hit return, run the other command, then pull the prefixed command from your history and continue....

Would be great if Atuin could lsupport this :)

**Comment by patricksjackson** [comment] 2022-11-17 01:25
This is also discussed in #467, so it seems like other people had or are having the same issue.

**Comment by ellie** [comment] 2023-10-18 03:07
Dupe of #467, as @arcuru said 😁

**Closed by ellie** 2023-10-18 03:07 UTC
