### ISSUE TITLE
select an entry and cd into that directory.

### ISSUE THREAD

**Issue by hongyi-zhao** [atuinsh/atuin#1844] opened 2024-03-10 12:50 UTC
Can I `select an entry and cd into that directory` with atuin, as done by [hiSHtory](https://github.com/ddworken/hishtory):

![image](https://github.com/atuinsh/atuin/assets/11155854/703f9b64-44e8-4d8c-beac-b69b0bb25b35)

By entering `ctrl+x`, it will give:

`werner@X10DAi:~$ cd "/home/werner/Public/repo/github.com/bash-it/custom" && git add 900.2-hishtory.git.bash.save`

Regards,
Zhao

**Comment by ellie** [comment] 2024-03-10 17:17
Dupe of #1842 

It's the weekend. Support is done on a best-effort basis and I like to actually take a break.

**Closed by ellie** 2024-03-10 17:17 UTC
