### ISSUE TITLE
History Search UI Overlaps and Persists in Terminal Window After Using `screen` Command

### ISSUE THREAD

**Issue by lemorage** [atuinsh/atuin#1303] opened 2023-10-11 19:19 UTC
**Describe the bug**
When using Atuin, an issue arises after the `screen` command. Specifically, the history search UI of Atuin will become overlapped with the current terminal window and persist even after new commands are initiated. This results in a cluttered and unclear terminal window unless you exit the current shell session.

**To Reproduce**
1. Use the `screen` command.
2. Invoke the history search UI of Atuin.

**Expected behavior**
The history search UI should not interfere with the visibility of the terminal window.

**Error logs**
N/A

**Device (please complete the following information):**
 - OS: macOS
 - Shell: zsh
 - Version: 16.0.0

**Self hosted**
N/A

**Additional context**

**Comment by ellie** [comment] 2023-10-11 22:55
Dupe of https://github.com/atuinsh/atuin/issues/320

**Closed by ellie** 2023-10-11 22:55 UTC
Labels: bug
