### ISSUE TITLE
Drop-in replacement for history cycling

### ISSUE THREAD

**Issue by musjj** [atuinsh/atuin#1464] opened 2023-12-28 14:42 UTC
In most shells, you can use `<C-n>`/`<C-p>` to cycle through the history. But it looks like that `atuin` doesn't provide any drop-in replacements for such functionality.

**Comment by ellie** [comment] 2023-12-28 19:29
I think we can consider this a dupe of #798

**Closed by ellie** 2023-12-28 19:29 UTC
